<?php
    $interval = $this->translate('report_interval_' . $this->reportGroup->getReportInterval());
?>

<?php if ($this->translate()->getLocale() == 'de') :?>
Bitte öffnen Sie Ihren <?php echo $interval; ?> Report "<?php echo $this->reportGroup->getTitle(); ?>", den Sie als Anhang zu dieser Email als Beistrich getrennte Datei (CSV) finden, welche Sie mit Microsoft Excel oder OpenOffice Calc öffnen können.

Um den Report online zu betrachten, klicken Sie bitte auf diesen <?php echo $this->serverUrl ?>/report/group/view/id/<?php echo$this->report->getItemId(); ?>. Sie müssen sich anmelden um den Report zu betrachten.

Ihr <?php echo $this->systemName; ?> Wlan Management System!
<?php else :?>

Please find your <?php echo $interval; ?> report "<?php echo $this->reportGroup->getTitle(); ?>" attached to this email as comma separated value (csv) file, which can be opened with spreadsheet software like Microsoft Excel or Openoffice Calc.

For looking at the report online, please follow this <?php echo $this->serverUrl ?>/report/group/view/id/<?php echo$this->report->getItemId(); ?>. You will need your login to view the report.

Your <?php echo $this->systemName; ?> wifi management system!

<?php endif; ?>