<a href="/report"><?php echo $this->translate('report_index_heading'); ?></a> &raquo;
<a href="/report/group/index/id/<?php echo $this->parent->getCodetemplateId()?>">Reports for <?php echo $this->parent_parent->getTitle();?> </a> &raquo;
<a href="/report/group/reports/id/<?php echo $this->parent->getReportGroupId()?>"><?php echo $this->parent->getTitle(); ?> Results</a>

<h1><?php echo $this->translate('report_group_heading'); ?> <?php echo $this->parent->getTitle(); ?></h1>

<table width="100%" class="listing">
<th colspan="4"><?php echo $this->translate('report_result_parameters'); ?></th>
<tr>
	<td><?php echo $this->translate('report_result_parameters_description'); ?></td><td colspan="3"><?php echo $this->parent->getDescription(); ?></td>
</tr>
<tr>
	<td><?php echo $this->translate('report_result_parameters_datefrom'); ?></td><td><?php echo $this->parent->getDateFrom();?></td><td><?php echo $this->translate('report_result_parameters_dateto'); ?></td><td><?php echo $this->parent->getDateFrom();?></td>
</tr>
<tr>
	<td><?php echo $this->translate('report_result_parameters_devicegroups'); ?></td><td colspan="3"><?php echo str_replace("\n", ", ", $this->parent->getGroupsAssignedFormatted());?></td>
</tr>
</table>


<?php
echo $this->paginationControl ( $this->paginator, 'Sliding', 'partial/pagination.phtml' );

$acl = Zend_Registry::get ( 'acl' );

?>

<div class="buttons span-18">

	<a id="addlink" class="button small green"
		href="<?php
		
		echo $this->url ( array ('action' => 'generate' ), null, false );
		?>"><span><?php echo $this->translate('report_group_button_generate');?></span></a>
</div>
<br />
<form class="span-19 last" method="get"
	action="<?php
	
	echo $this->url ( array ('module' => 'report', 'controller' => 'group', 'action' => 'index', 'id' => $this->parent->getTitle () ), null, true );
	?>">
	<table class="listing">
		<thead>
			<tr>
				<th><?php echo $this->translate('report_index_id');?></th>
				<th><?php echo $this->translate('report_index_date');?></th>
				<th><?php echo $this->translate('report_index_view');?></th>
				
			</tr>
		</thead>
		<tbody>
		<?php
		foreach ( $this->paginator as $user ) :
			?>
		<tr class="<?php echo $this->cycle(array('odd', 'even'))->next(); ?>">
				<td class="column_id"><?php echo $user->getItemId(); ?></td>
				<td><?php echo $user->getDateAdded(); ?></td>
				<td class="tools">
					
				  <?php
			$actions = array ('view', 'deleteresult');
			
			
				if (! $acl->isAllowed ( $this->currentUser, $user->getResourceId (), 'view' )) {
					continue;
				}
				
				?>
					<a
					href="<?php
				
				echo $this->url ( array ('module' => 'report', 'controller' => 'group', 'action' => 'view', 'id' => $user->getItemId () ), null, true );
				?>"
					class="icon view"><?php
				
				echo $this->translate ( 'report_group_button_view' );
				?></a>
				<?php 
				if (! $acl->isAllowed ( $this->currentUser, $user->getResourceId (), 'delete' )) {
					continue;
				}
				
				?>
					<a
					href="<?php
				
				echo $this->url ( array ('module' => 'report', 'controller' => 'group', 'action' => 'deleteresult', 'id' => $user->getItemId () ), null, true );
				?>"
					class="icon delete"><?php
				
				echo $this->translate ( 'report_group_button_view' );
				?></a
				
				</td>


			</tr>
		<?php endforeach; ?>
	</tbody>
	</table>
</form>

<?php echo $this->paginationControl($this->paginator, 'Sliding', 'partial/pagination.phtml'); ?>

<div class="buttons span-18">

	<a id="addlink" class="button small green"
		href="<?php
		
		echo $this->url ( array ('action' => 'generate' ), null, false );
		?>"><span><?php echo $this->translate('report_group_button_generate');?></span></a>
</div>
