<?php
/**
* Unwired AA GUI
*
* Author & Copyright (c) 2011 Unwired Networks GmbH
* alexander.szlezak@unwired.at
*
* Licensed under the terms of the Affero Gnu Public License version 3
* (AGPLv3 - http://www.gnu.org/licenses/agpl.html) or our proprietory
* license available at http://www.unwired.at/license.html
*/
?>
<div class="formelement">
&nbsp;
</div>
<div class="span-19 last formelement">

	<h1><?php echo $this->translate('rest_plugin_credentials_heading');?></h1>
	<div class="span-18 last">
		<label class="span-5"><?php echo $this->translate('rest_plugin_credentials_key');?>:</label> <label><?php echo $this->restKey->getKey(); ?></label>
	</div>
	<div class="span-18 last">
		<label class="span-5"><?php echo $this->translate('rest_plugin_credentials_secret');?>:</label> <label><?php echo $this->restKey->getSecret(); ?></label>
	</div>

</div>