<?php
	$this->headScript()->appendFile('http://maps.googleapis.com/maps/api/js?sensor=false');

	$this->headScript()->captureStart();
?>

	$(document).ready(function(){
		$('#nodemap').height(450);

		var latlng = new google.maps.LatLng(48.208, 16.373);
    	var myOptions = {
      		zoom: 12,
      		center: latlng,
      		mapTypeId: google.maps.MapTypeId.ROADMAP
    	};

    	var map = new google.maps.Map(document.getElementById("nodemap"),
        							  myOptions);

	});

<?php
	$this->headScript()->captureEnd();
?>

<div id="nodemap"></div>