<?php
	$this->headScript()->appendFile($this->httpScheme() . '://maps.googleapis.com/maps/api/js?sensor=false');

	$nodes = array();
	foreach ($this->nodes as $node) {
		$nodeArray = $node->toArray();
		unset($nodeArray['settings']);
		$nodes[] = $nodeArray;
	}
	$this->headScript()->captureStart();
?>
	var nodes = <?php echo Zend_Json::encode($nodes);?>;
	var map;
	var infowindow;

	function stringToDate(datestring)
	{
		var match = /(\d{4})\-0?(\d{1,2})\-0?(\d{1,2})\s0?(\d{1,2}):0?(\d{1,2}):0?(\d{1,2})/i.exec(datestring);

		if (!match.length) {
			return null;
		}

		var date = new Date();

		date.setFullYear(match[1]);
		date.setMonth(parseInt(match[2])-1);
		date.setDate(match[3]);
		date.setHours(match[4]);
		date.setMinutes(match[5]);
		date.setSeconds(match[6]);

		return date;
	}

	function formatDbDate(datestring)
	{
		if (datestring == '0000-00-00 00:00:00') {
			return 'unknown';
		}

		var match = /(\d{4})\-(\d{1,2})\-(\d{1,2})\s(\d{1,2}:\d{1,2}:\d{1,2})/i.exec(datestring);

		if (!match.length) {
			return '';
		}

		return match[3] + '/' + match[2] + '/' + match[1] + ' ' + match[4];
	}

	var lastDevice = null;

	var statsTimer = null;

	function loadStatistics(deviceData)
	{
		lastDevice = deviceData;

		$.ajax({
			url: '<?php echo $this->url(array('module' => 'default',
			                                  'controller' => 'index',
			                                  'action' => 'stats'), 'default', true)?>/location/' + deviceData.mac,
			success: function(data) {
				if (lastDevice !== deviceData) {
					return;
				}

				$('#infowindowcontainer div.stats').html(
					'<p><strong><?php echo $this->translate('default_index_index_ap_active_users')?>:</strong> ' + data.active_users + '</p>' +
					'<p><strong><?php echo $this->translate('default_index_index_ap_speed_up')?>:</strong> ' + data.total_kbps_up + '</p>' +
					'<p><strong><?php echo $this->translate('default_index_index_ap_speed_down')?>:</strong> ' + data.total_kbps_down + '</p>' +
					'<p><strong><?php echo $this->translate('default_index_index_ap_bytes_up')?>:</strong> ' + data.total_bytes_up + '</p>' +
					'<p><strong><?php echo $this->translate('default_index_index_ap_bytes_down')?>:</strong> ' + data.total_bytes_down + '</p>'
				);

				statsTimer = setTimeout("loadStatistics(deviceData);", 5000);
			}
		});
	}

	$(document).ready(function(){
		$('#nodemap').height(450);

		var latlng = new google.maps.LatLng(<?php echo $this->systemSettings['node_map_center_lat']->getValue(); ?>,
										    <?php echo $this->systemSettings['node_map_center_lng']->getValue(); ?>);
    	var myOptions = {
      		zoom: <?php echo (int) $this->systemSettings['node_map_zoom']->getValue(); ?>,
      		center: latlng,
      		mapTypeId: google.maps.MapTypeId.ROADMAP
    	};

    	map = new google.maps.Map(document.getElementById("nodemap"),
        							  myOptions);

		infowindow = new google.maps.InfoWindow();

		$.each(nodes, function(idx, data) {
			var mimage = "<?php echo $this->baseUrl("themes/" . $this->theme . "/images/icons/32x32/marker-red.png")?>";
			var onlinemsg = '';

			var formattedDate = formatDbDate(data.online_status_changed);

			if (data.online_status > 0) {
				onlinemsg = 'Online users: ' + data.online_users_count;
	    		onlinemsg = onlinemsg + '</div><div>Online since: ' + formattedDate;
	    		mimage = "<?php echo $this->baseUrl("themes/" . $this->theme . "/images/icons/32x32/marker-green.png")?>";
	    	} else {
	    		onlinemsg = 'Offline since: ' + formattedDate;
	    	}

			if (data.status == 'planning') {
				mimage = "<?php echo $this->baseUrl("themes/" . $this->theme . "/images/icons/32x32/marker-yellow.png")?>";
			}

			var marker = new google.maps.Marker({
		        position: new google.maps.LatLng(data.location.latitude, data.location.longitude),
		        title: data.name,
		        draggable: false,
		        icon: mimage
		    });



			marker.setMap(map);

		    google.maps.event.addListener(marker, 'click', function(event) {
		        if (statsTimer) {
		        	clearTimeout(statsTimer);
		        }

				infowindow.setContent('<div id="infowindowcontainer">' +
									  '<h5>' + marker.getTitle() +'</h5>' +
									  '<div>MAC: ' + data.mac + '</div>' +
									  '<div>Address: ' + data.location.address + ', ' + data.location.city +', ' + data.location.country + '</div>' +
									  '<div>' + onlinemsg + '</div>' +
									  '<div class="stats"></div>'+
									  '</div>');
				if (data.online_status > 0) {
					loadStatistics(data);
				}

				infowindow.open(map, marker);
		    });
		});
	});

<?php
	$this->headScript()->captureEnd();
?>

<div id="nodemap"></div>
