<?php
	$this->headScript()->appendFile($this->baseUrl('scripts/jquery.sparkline.min.js'));
	$this->headScript()->appendFile($this->httpScheme() . '://maps.googleapis.com/maps/api/js?sensor=false');

	$nodes = array();
	foreach ($this->nodes as $node) {
		$nodeArray = $node->toArray();
		unset($nodeArray['settings']);
		$nodes[] = $nodeArray;
	}
	$this->headScript()->captureStart();
?>
	var nodes = <?php echo Zend_Json::encode($nodes);?>;
	var map;
	var infowindow;

	function stringToDate(datestring)
	{
		var match = /(\d{4})\-0?(\d{1,2})\-0?(\d{1,2})\s0?(\d{1,2}):0?(\d{1,2}):0?(\d{1,2})/i.exec(datestring);

		if (!match.length) {
			return null;
		}

		var date = new Date();

		date.setFullYear(match[1]);
		date.setMonth(parseInt(match[2])-1);
		date.setDate(match[3]);
		date.setHours(match[4]);
		date.setMinutes(match[5]);
		date.setSeconds(match[6]);

		return date;
	}

	function formatDbDate(datestring)
	{
		if (datestring == '0000-00-00 00:00:00') {
			return 'unknown';
		}

		var match = /(\d{4})\-(\d{1,2})\-(\d{1,2})\s(\d{1,2}:\d{1,2}:\d{1,2})/i.exec(datestring);

		if (!match.length) {
			return '';
		}

		return match[3] + '/' + match[2] + '/' + match[1] + ' ' + match[4];
	}

	var lastDevice = null;

	var statsTimer = null;
	var networkTimer = null;

	var networkUpGraph = [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];
	var networkDownGraph = [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];

	function loadStatistics(deviceData)
	{
		lastDevice = deviceData;

		$.ajax({
			url: '<?php echo $this->url(array('module' => 'default',
			                                  'controller' => 'index',
			                                  'action' => 'stats'), 'default', true)?>/location/' + deviceData.mac,
			success: function(data) {
				if (lastDevice !== deviceData) {
					return;
				}

				if (data) {
    				$('#infowindowcontainer div.stats').html(
    					'<div><strong><?php echo $this->translate('default_index_index_ap_active_users')?>:</strong> ' + data.active_users + ' / ' + data.internet_users + ' / ' + data.active_internet_users + '</div>' +
    					'<div><strong><?php echo $this->translate('default_index_index_ap_speed_up')?>:</strong> ' + data.total_kbps_up + '</div>' +
    					'<div><strong><?php echo $this->translate('default_index_index_ap_speed_down')?>:</strong> ' + data.total_kbps_down + '</div>'
    				);
				}

				if ($('#infowindowcontainer').is(':visible')) {
 					statsTimer = setTimeout("loadStatistics(lastDevice);", 3000);
				}
			}
		});
	}

	function loadNetworkStatistics()
	{
		$.ajax({
			url: '<?php echo $this->url(array('module' => 'default',
			                                  'controller' => 'index',
			                                  'action' => 'stats',
			                                  'interface' => 'total'), 'default', true)?>',
			success: function(data) {

				if (data) {
				    // $('#devicesonline').text(online_ap_count);
					// $('#usersonline').text(data.active_users);
					$('#bandwidthup').text(data.kbps_tx);
					$('#bandwidthdown').text(data.kbps_rx);

					networkUpGraph.push(data.kbps_tx);
					networkUpGraph.splice(0,1);
					$('#networkgraphup').sparkline(networkUpGraph, { width: 510 })

					networkDownGraph.push(data.kbps_rx);
					networkDownGraph.splice(0,1);

					$('#networkgraphdown').sparkline(networkDownGraph, { width: 510 })
				}

 				networkTimer = setTimeout("loadNetworkStatistics();", 5000);
			}
		});
	}

	$(document).ready(function(){
		$('#nodemap').height(450);

		var latlng = new google.maps.LatLng(<?php echo $this->systemSettings['node_map_center_lat']->getValue(); ?>,
										    <?php echo $this->systemSettings['node_map_center_lng']->getValue(); ?>);
    	var myOptions = {
      		zoom: <?php echo (int) $this->systemSettings['node_map_zoom']->getValue(); ?>,
      		center: latlng,
      		mapTypeId: google.maps.MapTypeId.ROADMAP
    	};

    	map = new google.maps.Map(document.getElementById("nodemap"),
        							  myOptions);

		infowindow = new google.maps.InfoWindow();

		$.each(nodes, function(idx, data) {
			var mimage = "<?php echo $this->baseUrl("themes/" . $this->theme . "/images/icons/32x32/marker-red.png")?>";
			var onlinemsg = '';

			var formattedDate = formatDbDate(data.online_status_changed);



			if (data.online_status > 0) {
				onlinemsg = ''; // 'Online users: ' + data.online_users_count;
	    		onlinemsg = onlinemsg + '</div><div>Online since: ' + formattedDate;
	    		mimage = "<?php echo $this->baseUrl("themes/" . $this->theme . "/images/icons/32x32/marker-green.png")?>";
	    	} else {
	    		onlinemsg = 'Offline since: ' + formattedDate;
	    	}

			if (data.status == 'planning') {
				mimage = "<?php echo $this->baseUrl("themes/" . $this->theme . "/images/icons/32x32/marker-yellow.png")?>";
			}

			if (data.status == 'disabled') {
				mimage = "<?php echo $this->baseUrl("themes/" . $this->theme . "/images/icons/32x32/marker-grey.png")?>";
			}

			var marker = new google.maps.Marker({
		        position: new google.maps.LatLng(data.location.latitude, data.location.longitude),
		        title: data.name,
		        draggable: false,
		        icon: mimage
		    });



			marker.setMap(map);

		    google.maps.event.addListener(marker, 'click', function(event) {
		        if (statsTimer) {
		        	clearTimeout(statsTimer);
		        }

				infowindow.setContent('<div id="infowindowcontainer">' +
									  '<h5>' + marker.getTitle() +'</h5>' +
									  '<div>MAC: ' + data.mac + '</div>' +
									  '<div>Address: ' + data.location.address + ', ' + data.location.city +', ' + data.location.country + '</div>' +
									  '<div>' + onlinemsg + '</div>' +
				<?php if (isset($this->currentUser)) :?>
									  '<div class="stats">' +
									  '<div><strong><?php echo $this->translate('default_index_index_ap_active_users')?>:</strong> 0 / 0 / 0</div>' +
									  '<div><strong><?php echo $this->translate('default_index_index_ap_speed_up')?>:</strong> 0</div>' +
									  '<div><strong><?php echo $this->translate('default_index_index_ap_speed_down')?>:</strong> 0</div>' +
									  '</div>' +
									  '</div>');
				if (data.online_status > 0) {
					loadStatistics(data);
				}
				<?php else: ?>
									  '</div>');
				<?php endif; ?>
				infowindow.open(map, marker);
		    });
		});

		<?php if (isset($this->currentUser)) :?>
		loadNetworkStatistics();
		<?php endif; ?>
	});

<?php
	$this->headScript()->captureEnd();
?>

<div id="nodemap"></div>
<?php if (isset($this->currentUser)) :?>
<div id="networkstats">
	<div><strong><?php echo $this->translate('default_index_index_statistics')?>:</strong>
	<ul>
		<li><strong><?php echo $this->translate('default_index_index_devices')?>:</strong>
    		<ul>
    			<li><strong><?php echo $this->translate('default_index_index_devices_total')?></strong>: <span id="devicestotal"><?php echo $this->networkStats->getDevicesTotal(); ?></span></li>
    			<li><strong><?php echo $this->translate('default_index_index_devices_online')?></strong>: <span id="devicesonline"><?php echo $this->networkStats->getDevicesOnline(); ?></span></li>
    			<li><strong><?php echo $this->translate('default_index_index_devices_offline')?></strong>: <span id="devicesoffline"><?php echo $this->networkStats->getDevicesOffline(); ?></span></li>
    		</ul>
		</li>
    	<li>
    		<strong><?php echo $this->translate('default_index_index_users')?>:</strong>
    		<ul>
    			<li><strong><?php echo $this->translate('default_index_index_users_total')?></strong>: <span id="userstotal"><?php echo $this->networkStats->getUsersTotal(); ?></span></li>
    			<li><strong><?php echo $this->translate('default_index_index_users_online')?></strong>: <span id="usersonline"><?php echo $this->networkStats->getUsersOnline(); ?></span></li>
    			<li><strong><?php echo $this->translate('default_index_index_users_garden')?></strong>: <span id="usersgarden"><?php echo $this->networkStats->getUsersGarden(); ?></span></li>
    		</ul>
    	</li>
	</ul>
	</div>
	<div>
		<strong><?php echo $this->translate('default_index_index_bandwidth')?>:</strong>
		<ul>
			<li><strong><?php echo $this->translate('default_index_index_bandwidth_down')?>:</strong> <span id="bandwidthdown">0</span> <span id="networkgraphdown" class="span-13 last" style="float:right; text-align: right;"></span></li>
			<li><strong><?php echo $this->translate('default_index_index_bandwidth_up')?>:</strong> <span id="bandwidthup">0</span> <span id="networkgraphup" class="span-13 last" style="float:right; text-align: right;"></span></li>
		</ul>
	</div>
	<!-- <div><strong><?php echo $this->translate('default_index_index_bandwidth_up')?>:</strong> <span id="bandwidthup">0</span> <span id="networkgraphup" class="span-13 last" style="float:right; text-align: right;"></span></div>
	<div><strong><?php echo $this->translate('default_index_index_bandwidth_down')?>:</strong> <span id="bandwidthdown">0</span> <span id="networkgraphdown" class="span-13 last" style="float:right; text-align: right;"></span></div> -->
</div>
<?php endif; ?>