<h1><?php echo $this->translate('groups_role_index_heading'); ?></h1>

<?php
	$this->headScript()->appendFile($this->baseUrl('scripts/jstree/jquery.jstree.js'));
	$this->headLink()->appendStylesheet($this->baseUrl('scripts/jstree/themes/default/style.css'));
	$this->headScript()->captureStart();
?>
$(function () {
	var roleIds = new Array();

	$('li[id^=role_]').each(function(){
		roleIds.push($(this).attr('id'));
	});

    $(".roletree")
        .jstree({
            "plugins" : ["themes","html_data","ui"],
            "core" : { "initially_open" : roleIds },
            "ui" : { select_limit : 1 }
        })
        .bind("select_node.jstree", function (event, data) {
			var roleId = data.rslt.obj.attr("id").replace(/[^\d]+/gi,'');

			$.ajax({
				url: '<?php echo $this->url(array('module' => 'groups',
														  	  'controller' => 'role',
														  	  'action' => 'view')); ?>/id/' + roleId,
				'success' : function (viewdata) {
					$('#roleview').html(viewdata);

				},
				'error' : function() {
					/**
					 * @todo Add error message
					 */
					$('#roleview').html('');
				}
			})
	     })
});
<?php
	$this->headScript()->captureEnd();
?>
<div class="roletree span-8">
	<?php echo $this->tree($this->rootRole, null, array('prefix' => 'role_')); ?>
</div>
<div id="roleview" class="span-9">

</div>
<div class="buttons span-18">
	<?php
		$acl = Zend_Registry::get('acl');
		if ($acl->isAllowed($this->currentUser, $this->rootRole, 'add')) :
	?>

	<a class="button small green" href="<?php echo $this->url(array('action' => 'add'),
													   null,
													   false);
									?>"><span><?php echo $this->translate('groups_role_index_button_add');?></span></a>
	<?php
		endif;
	?>
</div>
