<h1><?php echo $this->translate('groups_role_index_heading'); ?></h1>

<table class="listing">
	<thead>
		<tr>
			<th><?php echo $this->translate('groups_role_index_id');?></th>
			<th><?php echo $this->translate('groups_role_index_name');?></th>
			<th class="tools">
			<a class="add" href="<?php
				echo $this->url(array('module' => 'groups',
									  'controller' => 'role',
									  'action' => 'add'), null, true);
				?>"><img src="<?php
					echo $this->baseUrl('themes/default/images/icons/24x24/add.png');
				?>" alt="<?php echo $this->translate('groups_role_index_button_add'); ?>" /> <?php echo $this->translate('groups_role_index_button_add'); ?></a>
			</th>
		</tr>
	</thead>
	<tbody>
		<?php foreach ($this->paginator as $role) :?>
		<tr class="<?php echo $this->cycle(array('odd', 'even'))->next(); ?>">
			<td class="column_id"><?php echo $role->getRoleId(); ?></td>
			<td><?php echo $role->getName(); ?></td>
			<td class="tools">
				<a class="edit" href="<?php
				echo $this->url(array('module' => 'groups',
									  'controller' => 'role',
									  'action' => 'edit',
									  'id'	=> $role->getRoleId()), null, true);
				?>"><img src="<?php
					echo $this->baseUrl('themes/default/images/icons/24x24/edit.png');
				?>" alt="<?php echo $this->translate('groups_role_index_button_edit'); ?>" /></a>

				<a class="delete" href="<?php
				echo $this->url(array('module' => 'groups',
									  'controller' => 'role',
									  'action' => 'delete',
									  'id'	=> $role->getRoleId()), null, true);
				?>"><img src="<?php
					echo $this->baseUrl('themes/default/images/icons/24x24/delete.png');
				?>" alt="<?php echo $this->translate('groups_role_index_button_delete'); ?>" /></a>
			</td>
		</tr>
		<?php endforeach; ?>
	</tbody>
</table>
<?php echo $this->paginationControl($this->paginator, 'Sliding', 'partial/pagination.phtml'); ?>