<?php
/**
* Unwired AA GUI
*
* Author & Copyright (c) 2011 Unwired Networks GmbH
* alexander.szlezak@unwired.at
*
* Licensed under the terms of the Affero Gnu Public License version 3
* (AGPLv3 - http://www.gnu.org/licenses/agpl.html) or our proprietory
* license available at http://www.unwired.at/license.html
*/
?>
<div class="span-17 formelement">
	<label><?php echo $this->translate('captive_content_edit_language'); ?>: <?php echo $this->languages[$this->languageId]->getName(); ?></label>
	<?php
	    if ($this->content->getContentId()) :
	?>
		<input type="hidden" name="<?php echo $this->prefix; ?>[content_id]" value="<?php echo $this->content->getContentId(); ?>" />
	<?php
	    endif;
	?>
	<input type="hidden" name="<?php echo $this->prefix; ?>[language_id]" value="<?php echo $this->languageId; ?>" />
</div>
<div class="formelement">
	<label><?php echo $this->translate('widget_iframe_admin_title'); ?>* :</label>
	<input type="text" name="<?php echo $this->prefix; ?>[title]" value="<?php echo $this->escape($this->content->getTitle()); ?>"/>
	<input type="hidden" name="<?php echo $this->prefix; ?>[column]" value="<?php echo $this->escape($this->content->getColumn()); ?>"/>
	<input type="hidden" name="<?php echo $this->prefix; ?>[order_web]" value="<?php echo $this->escape($this->content->getOrderWeb()); ?>"/>
	<input type="hidden" name="<?php echo $this->prefix; ?>[order_mobile]" value="<?php echo $this->escape($this->content->getOrderMobile()); ?>"/>
	<input type="hidden" name="<?php echo $this->prefix; ?>[widget]" value="Iframe"/>
</div>
<?php
    $targetId = rand(0,999) . '-' . $this->content->getContentId() . '-' . $this->languageId;
?>
<div class="span-18 last tabs subtabs">
    <ul class="span-18 last">
    	<li><a href="#desktop-<?php echo $targetId; ?>">Desktop</a></li>
    	<li><a href="#mobile-<?php echo $targetId; ?>">Mobile</a></li>
    </ul>
    <div id="desktop-<?php echo $targetId; ?>" class="subtabs-panel">
        <div class="formelement span-17 last">
        	<label><?php echo $this->translate('widget_iframe_admin_src'); ?>* :</label>
        	<input type="text" class="span-7 last" name="<?php echo $this->prefix; ?>[content][desktop][src]" value="<?php
        	    echo $this->escape($this->iframeData['desktop']['src']);
        	?>" />
        </div>
        <div class="formelement span-17 last">
        	<label><?php echo $this->translate('widget_iframe_admin_width'); ?>* :</label>
        	<input type="text" name="<?php echo $this->prefix; ?>[content][desktop][width]" value="<?php
        	    echo $this->escape($this->iframeData['desktop']['width']);
        	?>" />
        </div>
        <div class="formelement span-17 last">
        	<label><?php echo $this->translate('widget_iframe_admin_height'); ?>* :</label>
        	<input type="text" name="<?php echo $this->prefix; ?>[content][desktop][height]" value="<?php
        	    echo $this->escape($this->iframeData['desktop']['height']);
        	?>" />
        </div>
	</div>
    <div id="mobile-<?php echo $targetId; ?>" class="subtabs-panel">
        <div class="formelement span-17 last">
        	<label><?php echo $this->translate('widget_iframe_admin_src'); ?>* :</label>
        	<input type="text" class="span-7 last" name="<?php echo $this->prefix; ?>[content][mobile][src]" value="<?php
        	    echo $this->escape($this->iframeData['mobile']['src']);
        	?>" />
        </div>
        <div class="formelement span-17 last">
        	<label><?php echo $this->translate('widget_iframe_admin_width'); ?>* :</label>
        	<input type="text" name="<?php echo $this->prefix; ?>[content][mobile][width]" value="<?php
        	    echo $this->escape($this->iframeData['mobile']['width']);
        	?>" />
        </div>
        <div class="formelement span-17 last">
        	<label><?php echo $this->translate('widget_iframe_admin_height'); ?>* :</label>
        	<input type="text" name="<?php echo $this->prefix; ?>[content][mobile][height]" value="<?php
        	    echo $this->escape($this->iframeData['mobile']['height']);
        	?>" />
        </div>
	</div>
</div>