<h1><?php
	if ($this->entity->getUserId()) {
		echo sprintf($this->translate('users_netuser_edit_heading_edit'), $this->entity->getUsername());
	} else {
		echo $this->translate('users_netuser_edit_heading_add');
	}
?></h1>
<?php
	$this->headScript()->appendFile($this->baseUrl('scripts/jstree/jquery.jstree.js'));
	$this->headLink()->appendStylesheet($this->baseUrl('scripts/jstree/themes/default/style.css'));
	$this->headScript()->captureStart();
?>
$(function () {
	$("input[name=group_id]").hide().after($('.grouptree'));

    $(".grouptree")
        .jstree({
            "plugins" : ["themes","html_data","ui"],
            "core" : { "initially_open" : [ "group_<?php echo ($this->entity->getGroupId()); ?>" ] },
            "ui" : { select_limit : 1,  "initially_select" : [ "group_<?php echo ($this->entity->getGroupId()); ?>" ] }
        })
        .bind("select_node.jstree", function (event, data) {
			var groupId = data.rslt.obj.attr("id").replace(/[^\d]+/gi,'');

			$("input[name=group_id]").val(groupId);
	     })
});
<?php
	$this->headScript()->captureEnd();
?>
<?php echo $this->form;?>
<div class="grouptree span-8">
	<?php echo $this->tree($this->rootGroup, null, array('prefix' => 'group_')); ?>
</div>