<h1><?php echo $this->translate('users_netuser_index_heading'); ?></h1>

<?php
	echo $this->paginationControl($this->paginator, 'Sliding', 'partial/pagination.phtml');
	$acl = Zend_Registry::get('acl');
?>
<form class="span-19 last" method="get" action="<?php echo $this->url(array('module' => 'users',
													   'controller' => 'net-user',
													   'action' => 'index'),
												null,
												true); ?>">
<table class="listing">
	<thead>
		<tr>
			<th><?php echo $this->translate('users_netuser_index_id');?></th>
			<th><?php echo $this->translate('users_netuser_index_lastname');?></th>
			<th><?php echo $this->translate('users_netuser_index_firstname');?></th>
			<th><?php echo $this->translate('users_netuser_index_username');?></th>
			<th><?php echo $this->translate('users_netuser_index_mac');?></th>
			<th class="tools">
			<?php
			if ($acl->isAllowed($this->currentUser, 'users_netuser', 'add')) :
			?>
			<a class="add" href="<?php
				echo $this->url(array('module' => 'users',
									  'controller' => 'net-user',
									  'action' => 'add'), null, true);
				?>"><img src="<?php
					echo $this->baseUrl('themes/default/images/icons/24x24/add.png');
				?>" alt="<?php echo $this->translate('users_netuser_index_button_add'); ?>" /> <?php echo $this->translate('users_netuser_index_button_add'); ?></a>
			<?php
			endif;
			?>
			</th>
		</tr>
		<tr>
			<th></th>
			<th><input type="text" name="lastname" value="<?php echo $this->filter['lastname']; ?>" /></th>
			<th><input type="text" name="firstname" value="<?php echo $this->filter['firstname']; ?>" /></th>
			<th><input type="text" name="username" value="<?php echo $this->filter['username']; ?>" /></th>
			<th><input type="text" name="mac" value="<?php echo $this->filter['mac']; ?>" /></th>
			<th class="tools">
			<a name="index" class="icon filter"><?php echo $this->translate('users_netuser_index_button_filter'); ?></a>
			<a name="index" class="icon reset"><?php echo $this->translate('users_netuser_index_button_reset'); ?></a>
			</th>
		</tr>
	</thead>
	<tbody>
		<?php
		$macValidator = new Unwired_Validate_Mac();

		foreach ($this->paginator as $user) :
		?>
		<tr class="<?php echo $this->cycle(array('odd', 'even'))->next(); ?>">
			<td class="column_id"><?php echo $user->getUserId(); ?></td>
			<td><?php echo $user->getLastname(); ?></td>
			<td><?php echo $user->getFirstname(); ?></td>
			<td><?php echo $user->getUsername(); ?></td>
			<td><?php echo $user->getMac(); ?></td>
			<td class="tools">
				<?php
					$actions = array(/*'view',*/ 'edit', 'delete');
					if ($user->isRadiusSync()) {
						unset($actions[0]);
					}

					/**
					 * 3 => Disabled group
					 * @todo do some constant definition or somethings
					 */
					if (!in_array(3, $user->getPolicyIds())) {
						array_unshift($actions, array('edit' => 'disable'));
					} else {
						array_unshift($actions, array('edit' => 'enable'));
					}

					foreach ($actions as $action) :

						if (is_array($action)) {
							$permission = key($action);
							$action = current($action);
						} else {
							$permission = $action;
						}

						if (!$acl->isAllowed($this->currentUser, $user->getResourceId(), $permission)) {
							continue;
						}

						?>
					<a href="<?php echo $this->url(array('module' => 'users',
													     'controller' => 'net-user',
													     'action' => $action,
													     'id'	=> $user->getUserId()),
												   null,
												   true); ?>" class="icon <?php echo $action; ?>"><?php

						echo $this->translate('users_netuser_index_button_' . $action);
				   ?></a>
				   <?php
					endforeach;
				?>
			</td>
		</tr>
		<?php endforeach; ?>
	</tbody>
</table>
</form>
<?php echo $this->paginationControl($this->paginator, 'Sliding', 'partial/pagination.phtml'); ?>