<h1><?php echo $this->translate('users_netuser_index_heading'); ?></h1>

<?php echo $this->paginationControl($this->paginator, 'Sliding', 'partial/pagination.phtml'); ?>
<table class="listing">
	<thead>
		<tr>
			<th><?php echo $this->translate('users_netuser_index_id');?></th>
			<th><?php echo $this->translate('users_netuser_index_username');?></th>
			<th><?php echo $this->translate('users_netuser_index_firstname');?></th>
			<th><?php echo $this->translate('users_netuser_index_lastname');?></th>
			<th><?php echo $this->translate('users_netuser_index_city');?></th>
			<th><?php echo $this->translate('users_netuser_index_country');?></th>
			<th class="tools">
			<a class="add" href="<?php
				echo $this->url(array('module' => 'users',
									  'controller' => 'net-user',
									  'action' => 'add'), null, true);
				?>"><img src="<?php
					echo $this->baseUrl('themes/default/images/icons/24x24/add.png');
				?>" alt="<?php echo $this->translate('users_netuser_index_button_add'); ?>" /> <?php echo $this->translate('users_netuser_index_button_add'); ?></a>
			</th>
		</tr>
	</thead>
	<tbody>
		<?php
		$macValidator = new Unwired_Validate_Mac();
		$acl = Zend_Registry::get('acl');

		foreach ($this->paginator as $user) :
		?>
		<tr class="<?php echo $this->cycle(array('odd', 'even'))->next(); ?>">
			<td class="column_id"><?php echo $user->getUserId(); ?></td>
			<td><?php echo $user->getUsername(); ?></td>
			<td><?php echo $user->getFirstname(); ?></td>
			<td><?php echo $user->getLastname(); ?></td>
			<td><?php echo $user->getCity(); ?></td>
			<td><?php echo $user->getCountry(); ?></td>
			<td class="tools">
				<?php
					$actions = array(/*'view',*/ 'edit', 'delete');
					if ($macValidator->isValid($user->getUsername())) {
						unset($actions[0]);
					}

					foreach ($actions as $action) :
						if (!$acl->isAllowed($this->currentUser, $user->getResourceId(), $action)) {
							continue;
						}

						?>
					<a href="<?php echo $this->url(array('module' => 'users',
													     'controller' => 'net-user',
													     'action' => $action,
													     'id'	=> $user->getUserId()),
												   null,
												   true); ?>" class="icon <?php echo $action; ?>"><?php

						echo $this->translate('users_netuser_index_button_' . $action);
				   ?></a>
				   <?php
					endforeach;
				?>
			</td>
		</tr>
		<?php endforeach; ?>
	</tbody>
</table>
<?php echo $this->paginationControl($this->paginator, 'Sliding', 'partial/pagination.phtml'); ?>