<h1><?php echo $this->translate('default_log_index_heading'); ?></h1>

<?php
	echo $this->paginationControl($this->paginator, 'Sliding', 'partial/pagination.phtml');

	$acl = Zend_Registry::get('acl');
?>
<form class="span-19 last" method="get" action="<?php echo $this->url(array('module' => 'default',
													   'controller' => 'log',
													   'action' => 'index'),
												null,
												true); ?>">
<table class="listing">
	<thead>
		<tr>
			<th><?php echo $this->translate('default_log_index_id');?></th>
			<th class="span-5 last"><?php echo $this->translate('default_log_index_user');?></th>
			<th class="span-3 last"><?php echo $this->translate('default_log_index_event');?></th>
			<th class="span-3 last"><?php echo $this->translate('default_log_index_entity');?></th>
			<th class="span-2 last"><?php echo $this->translate('default_log_index_entity_id');?></th>
			<th><?php echo $this->translate('default_log_index_remote');?></th>
			<th><?php echo $this->translate('default_log_index_timestamp');?></th>
		</tr>
		<tr>
			<th></th>
			<th><input type="text" name="email" value="<?php echo $this->filter['email']; ?>" /></th>
			<th>
			<select class="span-3 last" name="event_id">
					<option value=""><?php echo $this->translate('default_log_index_event_all'); ?></option>
			<?php
				$events = $this->logDistinctPairs('event');
				foreach ($events as $id => $name) :
			?>
				<option <?php
							echo ($this->filter['event_id'] == $id) ? 'selected="selected"' : '';
						?> value="<?php echo $id; ?>"><?php echo $this->translate($name); ?></option>
			<?php
				endforeach;
			?>
				</select>
			</th>
			<th><select class="span-3 last" name="entity">
					<option value=""><?php echo $this->translate('default_log_index_entity_all'); ?></option>
			<?php
				$entities = $this->logDistinctPairs('entity');
				foreach ($entities as $id => $name) :
			?>
				<option <?php
							echo ($this->filter['entity'] == $id) ? 'selected="selected"' : '';
						?> value="<?php echo $id; ?>"><?php echo $this->translate($name); ?></option>
			<?php
				endforeach;
			?>
				</select>
			</th>
			<th>
				<input type="text" name="entity_id" value="<?php echo $this->filter['entity_id']; ?>" />
			</th>
			<th><input type="text" name="remote_host" value="<?php echo $this->filter['remote_host']; ?>" /></th>
			<th class="tools">
			<a name="index" class="icon filter"><?php echo $this->translate('default_log_index_button_filter'); ?></a>
			<a name="index" class="icon reset"><?php echo $this->translate('default_log_index_button_reset'); ?></a>
			</th>
		</tr>
	</thead>
	<tbody>
		<?php
			$filter = new Zend_Filter_Word_CamelCaseToUnderscore();
			foreach ($this->paginator as $log) :
		?>
		<tr class="<?php echo $this->cycle(array('odd', 'even'))->next(); ?>">
			<td class="span-2"><?php echo $log->getLogId(); ?></td>
			<td><?php
				if ($log->getUserId()) :

					$admin = $this->findAdmin($log->getUserId());

					if ($admin) {
						echo $admin->getEmail();
					}
				endif;
				?>
			</td>
			<td><?php echo $log->getEventName(); ?></td>
			<td><?php
				if ($log->getEntityId()):
					try {
					    $entity = null;
						$class = $log->getEntityName();

						if (class_exists($class)) {
						    $entity = new $class;
						}
						
						if ($entity) :
							$classParts = explode('_', $class);
							if ($classParts[0] == $classParts[2] || $classParts[0] == $classParts[2] . 's') {
								$classParts[2] = 'index';
							}
							?>
							<a href="<?php echo $this->url(array('module' => strtolower($filter->filter($classParts[0])),
																'controller' => strtolower($filter->filter($classParts[2])),
																'action' => 'edit',
																'id' => $log->getEntityId()),
														  'default',
														  true); ?>"><?php 
						endif;

						echo ($entity && $entity instanceof Zend_Acl_Resource_Interface)
							 ? $this->translate('resource_' . $entity->getResourceId())
							 : $this->translate($log->getEntityName());

						// echo ' : ';

						$eventData = $log->getEventData();
						if (!empty($eventData)) {
							$entityData = @unserialize($eventData);
							if (is_array($entityData)) {
								foreach ($eventData as $key => $value) {
									if (null === $value) {
										unset($eventData[$key]);
									}
								}
								$entity->fromArray(unserialize($eventData));
							}
						} else {
							$entity = null;
						}

						if (method_exists($entity, 'getName')) {

							echo ' : ' . $entity->getName();
						} /*else {
							echo $log->getEntityId();
						}*/
						
					} catch (Exception $e) {
						// nothing
					}
					
					if ($entity) :
						?></a><?php 
					endif;

				endif;
			?></td>
			<td>
				<?php echo $log->getEntityId(); ?>
			</td>
			<td><?php echo $log->getRemoteHost(); ?></td>
			<td><?php echo $log->getStamp(); ?></td>
		</tr>
		<?php endforeach; ?>
	</tbody>
</table>
</form>
<?php echo $this->paginationControl($this->paginator, 'Sliding', 'partial/pagination.phtml'); ?>
