<h1><?php echo $this->translate('nodes_index_index_heading'); ?></h1>

<table class="listing">
	<thead>
		<tr>
			<th><?php echo $this->translate('nodes_index_index_id');?></th>
			<th><?php echo $this->translate('nodes_index_index_name');?></th>
			<th><?php echo $this->translate('nodes_index_index_mac');?></th>
			<th><?php echo $this->translate('nodes_index_index_status');?></th>
			<th class="tools">
			<a class="add" href="<?php
				echo $this->url(array('module' => 'nodes',
									  'controller' => 'index',
									  'action' => 'add'), null, true);
				?>"><img src="<?php
					echo $this->baseUrl('themes/default/images/icons/24x24/add.png');
				?>" alt="<?php echo $this->translate('nodes_index_index_button_add'); ?>" /> <?php echo $this->translate('nodes_index_index_button_add'); ?></a>
			</th>
		</tr>
	</thead>
	<tbody>
		<?php foreach ($this->paginator as $node) :?>
		<tr class="<?php echo $this->cycle(array('odd', 'even'))->next(); ?>">
			<td class="column_id"><?php echo $node->getNodeId(); ?></td>
			<td><?php echo $node->getName(); ?></td>
			<td><?php echo $node->getMac(); ?></td>
			<td><?php echo $node->getStatus(); ?></td>
			<td class="tools">
				<a class="edit" href="<?php
				echo $this->url(array('module' => 'nodes',
									  'controller' => 'index',
									  'action' => 'edit',
									  'id'	=> $node->getNodeId()), null, true);
				?>"><img src="<?php
					echo $this->baseUrl('themes/default/images/icons/24x24/edit.png');
				?>" alt="<?php echo $this->translate('nodes_index_index_button_edit'); ?>" /></a>

				<a class="delete" href="<?php
				echo $this->url(array('module' => 'nodes',
									  'controller' => 'index',
									  'action' => 'delete',
									  'id'	=> $node->getNodeId()), null, true);
				?>"><img src="<?php
					echo $this->baseUrl('themes/default/images/icons/24x24/delete.png');
				?>" alt="<?php echo $this->translate('nodes_index_index_button_delete'); ?>" /></a>
			</td>
		</tr>
		<?php endforeach; ?>
	</tbody>
</table>