<h1><?php echo $this->translate('nodes_index_index_heading'); ?></h1>

<?php echo $this->paginationControl($this->paginator, 'Sliding', 'partial/pagination.phtml'); ?>
<table class="listing">
	<thead>
		<tr>
			<th><?php echo $this->translate('nodes_index_index_operator');?></th>
			<th><?php echo $this->translate('nodes_index_index_name');?></th>
			<th><?php echo $this->translate('nodes_index_index_mac');?></th>
			<th><?php echo $this->translate('nodes_index_index_wanip');?></th>
			<th><?php echo $this->translate('nodes_index_index_status');?></th>
			<th class="tools">
			<a class="add" href="<?php
				echo $this->url(array('module' => 'nodes',
									  'controller' => 'index',
									  'action' => 'add'), null, true);
				?>"><img src="<?php
					echo $this->baseUrl('themes/default/images/icons/24x24/add.png');
				?>" alt="<?php echo $this->translate('nodes_index_index_button_add'); ?>" /> <?php echo $this->translate('nodes_index_index_button_add'); ?></a>
			</th>
		</tr>
	</thead>
	<tbody>
		<?php
			$acl = Zend_Registry::get('acl');

			foreach ($this->paginator as $node) :
		?>
		<tr class="<?php echo $this->cycle(array('odd', 'even'))->next(); ?>">
			<?php
				$parent = $last = $operator = $node->getGroup();

				while ($parent = $parent->getParent()) {
					$operator = $last;
					$last = $parent;
				}
			?>
			<td class="column_id"><?php echo $operator->getName(); ?></td>
			<td><?php echo $node->getName(); ?></td>
			<td><?php echo $node->getMac(); ?></td>
			<td><?php echo $node->getSettings()->getIpaddress(); ?></td>
			<td><?php echo $node->getStatus(); ?></td>
			<td class="tools">
				<?php
					$actions = array(/*'view',*/ 'edit', 'delete');

					foreach ($actions as $action) :
						if (!$acl->isAllowed($this->currentUser, $node->getResourceId(), $action)) {
							continue;
						}

						?>
					<a href="<?php echo $this->url(array('module' => 'nodes',
													     'controller' => 'index',
													     'action' => $action,
													     'id'	=> $node->getNodeId()),
												   null,
												   true); ?>" class="icon <?php echo $action; ?>"><?php

						echo $this->translate('nodes_index_index_button_' . $action);
				   ?></a>
				   <?php
					endforeach;
				?>
			</td>
		</tr>
		<?php endforeach; ?>
	</tbody>
</table>
<?php echo $this->paginationControl($this->paginator, 'Sliding', 'partial/pagination.phtml'); ?>