<h1><?php echo $this->translate('nodes_index_index_heading'); ?></h1>

<?php
	$this->headScript()->appendFile($this->baseUrl('scripts/fancybox/jquery.fancybox-1.3.4.pack.js'));
	$this->headLink()->appendStylesheet($this->baseUrl('scripts/fancybox/jquery.fancybox-1.3.4.css'));
	echo $this->paginationControl($this->paginator, 'Sliding', 'partial/pagination.phtml');
	$acl = Zend_Registry::get('acl');
	$this->headScript()->captureStart();
?>
$(document).ready(function(){
	$('#groupfilterlink').fancybox();
});
<?php
	$this->headScript()->captureEnd();
?>
<form class="span-19 last" method="get" action="<?php echo $this->url(array('module' => 'nodes',
													   'controller' => 'index',
													   'action' => 'index'),
												null,
												true); ?>">
<table class="listing">
	<thead>
		<tr>
			<th><?php echo $this->translate('nodes_index_index_operator');?></th>
			<th><?php echo $this->translate('nodes_index_index_name');?></th>
			<th><?php echo $this->translate('nodes_index_index_mac');?></th>
			<th><?php echo $this->translate('nodes_index_index_wanip');?></th>
			<th><?php echo $this->translate('nodes_index_index_billable');?></th>
			<th><?php echo $this->translate('nodes_index_index_status');?></th>
			<th><?php echo $this->translate('nodes_index_index_online');?></th>
			<th><?php echo $this->translate('nodes_index_index_onlineusers');?></th>
			<th class="tools">
			<?php
			if ($acl->isAllowed($this->currentUser, 'nodes_node', 'add')) :
			?>
			<a class="add" href="<?php
				echo $this->url(array('module' => 'nodes',
									  'controller' => 'index',
									  'action' => 'add'), null, true);
				?>"><img src="<?php
					echo $this->baseUrl('themes/default/images/icons/24x24/add.png');
				?>" alt="<?php echo $this->translate('nodes_index_index_button_add'); ?>" /> <?php echo $this->translate('nodes_index_index_button_add'); ?></a>
			<?php
			endif;
			?>
			</th>
		</tr>
		<tr>
			<th><a href="#groupfilter" id="groupfilterlink"><?php echo $this->translate('nodes_index_index_group_filter'); ?></a></th>
			<th><input type="text" name="name" value="<?php echo $this->filter['name']; ?>" /></th>
			<th><input type="text" name="mac" value="<?php echo $this->filter['mac']; ?>" /></th>
			<th><input type="text" name="ipaddress" value="<?php echo $this->filter['ipaddress']; ?>" /></th>
			<th>
				<select name="billable">
					<option value=""><?php echo $this->translate('nodes_index_index_billable_all')?></option>
					<option value="1" <?php echo ($this->filter['billable'] == 1) ? 'selected="selected"' : ''; ?>><?php echo $this->translate('nodes_index_index_billable_yes')?></option>
					<option value="0" <?php echo ($this->filter['billable'] != '' && $this->filter['billable'] == 0) ? 'selected="selected"' : ''; ?>><?php echo $this->translate('nodes_index_index_billable_no')?></option>
				</select>
			</th>
			<th></th>
			<th></th>
			<th></th>
			<th class="tools">
			<a name="index_index" class="icon filter"><?php echo $this->translate('nodes_index_index_button_filter'); ?></a>
			<a name="index_index" class="icon reset"><?php echo $this->translate('nodes_index_index_button_reset'); ?></a>
			</th>
		</tr>
	</thead>
	<tbody>
		<?php
			foreach ($this->paginator as $node) :
		?>
		<tr class="<?php echo $this->cycle(array('odd', 'even'))->next(); ?>">
			<?php
				$parent = $last = $operator = $node->getGroup();

				while ($parent = $parent->getParent()) {
					$operator = $last;
					$last = $parent;
				}
			?>
			<td class="column_id"><?php echo $operator->getName(); ?></td>
			<td><?php echo $node->getName(); ?></td>
			<td><?php echo $node->getMac(); ?></td>
			<td><?php echo $node->getSettings()->getIpaddress(); ?></td>
			<td style="text-align: center;"><img alt="" src="<?php echo $this->baseUrl('themes/' . $this->theme . '/images/icons/16x16/status' . $node->isBillable() . '.png'); ?>" /></td>
			<td><?php echo $this->translate('nodes_index_edit_form_status_' . $node->getStatus()); ?></td>
			<td><?php echo $this->onlineStatusSince($node); ?></td>
			<td><?php echo $node->getOnlineUsersCount(); ?></td>
			<td class="tools">
				<?php
					$actions = array('view', 'edit', 'delete');

					foreach ($actions as $action) :
						if (!$acl->isAllowed($this->currentUser, $node->getResourceId(), $action)) {
							continue;
						}

						?>
					<a href="<?php echo $this->url(array('module' => 'nodes',
													     'controller' => 'index',
													     'action' => $action,
													     'id'	=> $node->getNodeId()),
												   null,
												   true); ?>" class="icon <?php echo $action; ?>"><?php

						echo $this->translate('nodes_index_index_button_' . $action);
				   ?></a>
				   <?php
					endforeach;
				?>
			</td>
		</tr>
		<?php endforeach; ?>
	</tbody>
</table>
</form>
<?php echo $this->partial('index/groups-filter.phtml', 'nodes', array('rootGroup' => $this->rootGroup)); ?>
<?php echo $this->paginationControl($this->paginator, 'Sliding', 'partial/pagination.phtml'); ?>