<?php
/**
* Unwired AA GUI
*
* Author & Copyright (c) 2011 Unwired Networks GmbH
* alexander.szlezak@unwired.at
*
* Licensed under the terms of the Affero Gnu Public License version 3
* (AGPLv3 - http://www.gnu.org/licenses/agpl.html) or our proprietory
* license available at http://www.unwired.at/license.html
*/

echo $this->paginatorToXml($this->paginator, 'devices', 'device', array('node_id' => 'id'), array('settings',
																								  'update_config',
                                                                                                  'location' => array('node_id'),
                                                                                                  'group',
																								  'deleted'));
?>