<h1><?php echo $this->translate('nodes_index_showgroup_heading', $this->group->getName()); ?></h1>

<?php
	echo $this->paginationControl($this->paginator, 'Sliding', 'partial/pagination.phtml');
	$acl = Zend_Registry::get('acl');
?>
<form class="span-19 last" method="GET" action="<?php echo $this->url(array('module' => 'nodes',
													   'controller' => 'index',
													   'action' => 'show-group',
													   'id' => $this->group->getGroupId()),
												null,
												true); ?>">
<table class="listing">
	<thead>
		<tr>
			<th><?php echo $this->translate('nodes_index_showgroup_operator');?></th>
			<th><?php echo $this->translate('nodes_index_index_name');?></th>
			<th><?php echo $this->translate('nodes_index_index_mac');?></th>
			<th><?php echo $this->translate('nodes_index_index_wanip');?></th>
			<th><?php echo $this->translate('nodes_index_index_status');?></th>
			<th class="tools">
			<?php
			if ($acl->isAllowed($this->currentUser, 'nodes_node', 'add')) :
			?>
			<a class="add" href="<?php
				echo $this->url(array('module' => 'nodes',
									  'controller' => 'index',
									  'action' => 'add',
									  'group_id' => $this->group->getGroupId()), null, true);
				?>"><img src="<?php
					echo $this->baseUrl('themes/default/images/icons/24x24/add.png');
				?>" alt="<?php echo $this->translate('nodes_index_index_button_add'); ?>" /> <?php echo $this->translate('nodes_index_index_button_add'); ?></a>
			<?php
			endif;
			?>
			</th>
		</tr>
		<tr>
			<th></th>
			<th><input type="text" name="name" value="<?php echo $this->filter['name']; ?>" /></th>
			<th><input type="text" name="mac" value="<?php echo $this->filter['mac']; ?>" /></th>
			<th><input type="text" name="ipaddress" value="<?php echo $this->filter['ipaddress']; ?>" /></th>
			<th></th>
			<th class="tools">
			<a name="index/show-group" class="icon filter"><?php echo $this->translate('nodes_index_index_button_filter'); ?></a>
			<a name="index/show-group" class="icon reset"><?php echo $this->translate('nodes_index_index_button_reset'); ?></a>
			</th>
		</tr>
	</thead>
	<tbody>
		<?php
			foreach ($this->paginator as $node) :
		?>
		<tr class="<?php echo $this->cycle(array('odd', 'even'))->next(); ?>">
			<?php
				/* $parent = $last = $operator = $node->getGroup();

				while ($parent = $parent->getParent()) {
					$operator = $last;
					$last = $parent;
				} */
			?>
			<td class="column_id"><?php echo $this->group->getName(); ?></td>
			<td><?php echo $node->getName(); ?></td>
			<td><?php echo $node->getMac(); ?></td>
			<td><?php echo $node->getSettings()->getIpaddress(); ?></td>
			<td><?php echo $node->getStatus(); ?></td>
			<td class="tools">
				<?php
					$actions = array(/*'view',*/ 'edit', 'delete');

					foreach ($actions as $action) :
						if (!$acl->isAllowed($this->currentUser, $node->getResourceId(), $action)) {
							continue;
						}

						?>
					<a href="<?php echo $this->url(array('module' => 'nodes',
													     'controller' => 'index',
													     'action' => $action,
													     'id'	=> $node->getNodeId()),
												   null,
												   true); ?>" class="icon <?php echo $action; ?>"><?php

						echo $this->translate('nodes_index_index_button_' . $action);
				   ?></a>
				   <?php
					endforeach;
				?>
			</td>
		</tr>
		<?php endforeach; ?>
	</tbody>
</table>
</form>
<?php echo $this->paginationControl($this->paginator, 'Sliding', 'partial/pagination.phtml'); ?>