<h1><?php
	if ($this->entity->getGroupId()) {
		echo sprintf($this->translate('groups_group_edit_heading_edit'), $this->entity->getName());
	} else {
		echo $this->translate('groups_group_edit_heading_add');
	}
?></h1>
<?php
	$this->headScript()->appendFile($this->baseUrl('scripts/jstree/jquery.jstree.js'));
	$this->headLink()->appendStylesheet($this->baseUrl('scripts/jstree/themes/default/style.css'));
	$this->headScript()->captureStart();
?>
var adminGroups = <?php echo Zend_Json::encode($this->currentUser->getGroupsAssigned());?>;
$(function () {
	$("input[name=parent_id]").hide().after($('.grouptree'));
    <?php if ($this->entity->getParentId()) : ?>
    $(".grouptree")
        .jstree({
            "plugins" : ["themes","html_data","ui"],
            "core" : { "initially_open" : [ "group_<?php echo ($this->entity->getParentId() ? $this->entity->getParentId() : 1); ?>" ] },
            "ui" : { select_limit : 1,  "initially_select" : [ "group_<?php echo ($this->entity->getParentId()); ?>" ] }
        })
        .bind("select_node.jstree", function (event, data) {
			var groupId = data.rslt.obj.attr("id").replace(/[^\d]+/gi,'');

			$("input[name=parent_id]").val(groupId);
	     });
	 <?php else: ?>
	 $("input[name=parent_id]").parent().hide();
	 <?php endif;?>
});
<?php
	$this->headScript()->captureEnd();
?>
<?php echo $this->form;?>
<div class="grouptree span-8">
	<?php echo $this->tree($this->rootGroup, $this->entity, array('prefix' => 'group_')); ?>
</div>