<h1><?php echo $this->translate('groups_group_index_heading'); ?></h1>

<?php
	$this->headScript()->appendFile($this->baseUrl('scripts/jstree/jquery.jstree.js'));
	$this->headLink()->appendStylesheet($this->baseUrl('scripts/jstree/themes/default/style.css'));
	$this->headScript()->captureStart();
?>
$(function () {
    $(".grouptree")
        .jstree({
            "plugins" : ["themes","html_data","ui"],
            "core" : { "initially_open" : [ "group_1" ] },
            "ui" : { select_limit : 1 }
        })
        .bind("select_node.jstree", function (event, data) {
			var groupId = data.rslt.obj.attr("id").replace(/[^\d]+/gi,'');

			$.ajax({
				url: '<?php echo $this->url(array('module' => 'groups',
														  	  'controller' => 'index',
														  	  'action' => 'view')); ?>/id/' + groupId,
				'success' : function (viewdata) {
					$('#groupview').html(viewdata);

				},
				'error' : function() {
					/**
					 * @todo Add error message
					 */
					$('#groupview').html('');
				}
			})
	     })
});
<?php
	$this->headScript()->captureEnd();
?>
<div class="grouptree span-8">
	<?php echo $this->tree($this->rootGroup, null, array('prefix' => 'group_')); ?>
</div>
<div id="groupview" class="span-9">

</div>
<div class="buttons span-18">
	<a class="button small green" href="<?php echo $this->url(array('action' => 'add'),
													   null,
													   false);
									?>"><span><?php echo $this->translate('groups_group_index_button_add');?></span></a>
</div>
