<h1><?php echo $this->translate('groups_group_listing'); ?></h1>

<?php
	$this->headScript()->appendFile('scripts/jstree/jquery.jstree.js');
	$this->headLink()->appendStylesheet('scripts/jstree/themes/default/style.css');
	$this->headScript()->captureStart();
?>
$(function () {
	    // TO CREATE AN INSTANCE
	    // select the tree container using jQuery
	    $(".grouptree")
	        // call `.jstree` with the options object
	        .jstree({
	            // the `plugins` array allows you to configure the active plugins on this instance
	            "plugins" : ["themes","html_data","ui","crrm"],
	        })
	        // EVENTS
	        // each instance triggers its own events - to process those listen on the container
	        // all events are in the `.jstree` namespace
	        // so listen for `function_name`.`jstree` - you can function names from the docs
	        .bind("loaded.jstree", function (event, data) {
	            // you get two params - event & data - check the core docs for a detailed description
	        });
	});
<?php
	$this->headScript()->captureEnd();
?>
<div class="grouptree">
	<?php echo $this->groupTree($this->rootGroup); ?>
</div>