<?php
	$this->layout()->disableLayout();
?>
<div>
	<span><?php echo $this->translate('groups_group_view_name')?>:</span>
	<strong><?php echo $this->group->getName(); ?></strong>
</div>

<div>
	<span><?php echo $this->translate('groups_group_view_parents')?>:</span>
	<?php
		$group = $this->group;
		$top = null;
		while ($parent = $group->getParent()) {
			$top = $parent;
			$group = $parent;
		}
		echo $this->tree($top, $this->group, array('prefix' => 'group_'));
	?>
</div>

<div class="buttons">
	<?php
		$acl = Zend_Registry::get('acl');
		if ($acl->isAllowed($this->currentUser, $this->group, 'view')) :
	?>
	<a class="button small green" href="<?php echo $this->url(array('module' => 'nodes',
																   'controller' => 'index',
																   'action' => 'show-group',
									     						   'id' => $this->group->getGroupId()),
										   null,
										   true); ?>"><span><?php echo $this->translate('groups_group_view_button_nodes');?></span></a>
	<?php
		endif;

		if ($acl->isAllowed($this->currentUser, $this->group, 'edit')) :
	?>
	<a class="button small blue" href="<?php echo $this->url(array('action' => 'edit',
									     					 'id' => $this->group->getGroupId()),
										   null,
										   false); ?>"><span><?php echo $this->translate('groups_group_view_button_edit');?></span></a>
	<?php
		endif;

		if ($acl->isAllowed($this->currentUser, $this->group, 'delete')) :
	?>
	<a class="button small red" href="<?php echo $this->url(array('action' => 'delete',
											     'id' => $this->group->getGroupId()),
										   null,
										   false); ?>"><span><?php echo $this->translate('groups_group_view_button_delete');?></span></a>
	<?php
		endif;
	?>
</div>