<a href="<?php echo $this->url(array('module' => 'reports'), null, true); ?>"><?php echo $this->translate('report_index_heading'); ?></a> &raquo;
<a href="<?php echo $this->url(array('module' => 'reports',
                                     'controller' => 'group',
                                     'id' => $this->parent->getCodetemplateId()), null, true);
        ?>">Reports for <?php echo $this->parent->getTitle();?> </a>
<br /><br />
<h1><?php echo $this->translate('report_group_heading'); ?> <?php echo $this->parent->getTitle(); ?></h1>

<?php
echo $this->paginationControl($this->paginator, 'Sliding', 'partial/pagination.phtml');

$acl = Zend_Registry::get('acl');

?>
<form class="span-19 last" method="get"
	action="<?php

	echo $this->url ( array ('module' => 'reports', 'controller' => 'group', 'action' => 'index', 'id' => $this->parent->getCodetemplateId () ), null, true );
	?>">
	<table class="listing">
		<thead>
			<tr>
				<th><?php echo $this->translate('report_index_id');?></th>
				<th><?php echo $this->translate('report_index_title');?></th>
				<th><?php echo $this->translate('report_index_from');?></th>
				<th><?php echo $this->translate('report_index_to');?></th>
				<th><?php echo $this->translate('report_index_devices');?></th>
				<th class="tools">
                    <?php
        			    if ($acl->isAllowed($this->currentUser, 'reports_group', 'add')) :
        			?>
						<a class="add" href="<?php
            				echo $this->url(array('module' => 'reports',
            									  'controller' => 'group',
            									  'action' => 'add',
            				                      'id' => $this->parent->getCodeTemplateId()), null, true);
            				?>"><img src="<?php
        					echo $this->baseUrl('themes/default/images/icons/24x24/add.png');
        				    ?>" alt="<?php echo $this->translate('report_group_add'); ?>" /> <?php echo $this->translate('report_group_add'); ?></a>
					<?php endif; ?>

				</th>

			</tr>
			<tr>
				<th></th>
				<th colspan="1"><input type="text" name="title"
					value="<?php echo $this->filter['title']; ?>" /></th>
				<th>&nbsp;</th>
				<th>&nbsp;</th>
				<th>&nbsp;</th>
				<th class="tools"><a name="index" class="icon filter"><?php echo $this->translate('report_index_button_filter'); ?></a>
					<a name="index" class="icon reset"><?php echo $this->translate('report_index_button_reset'); ?></a>
				</th>
			</tr>
		</thead>
		<tbody>
		<?php
		foreach ($this->paginator as $reportGroup) :
		?>
		<tr class="<?php echo $this->cycle(array('odd', 'even'))->next(); ?>">
				<td class="column_id"><?php echo $reportGroup->getReportGroupId(); ?></td>
				<td><?php echo $reportGroup->getTitle(); ?></td>
				<td><?php echo $reportGroup->getDateFrom(); ?></td>
				<td><?php echo $reportGroup->getDateTo(); ?></td>
				<td><?php echo nl2br($reportGroup->getGroupsAssignedFormatted()); ?></td>
				<td class="tools">
				  <?php
			$actions = array(
			                array('action' => 'reports', 'permission' => 'view'),
			                array('action' => 'generate', 'permission' => 'add', 'resource' => 'reports_items'),
			                'delete'
			           );

			foreach ($actions as $action) :
			    if (is_array($action)) {
			        $permission = $action['permission'];
			        $resource = isset($action['resource']) ? $action['resource'] : $reportGroup->getResourceId();
			        $action = $action['action'];
			    } else {
			        $permission = $action;
			        $resource = $reportGroup->getResourceId();
			    }

				if (!$acl->isAllowed($this->currentUser, $resource, $permission)) {
					continue;
				}

				?>
					<a
					href="<?php

				echo $this->url(array('module' => 'reports',
				                      'controller' => 'group',
				                      'action' => $action,
				                      'id' => $reportGroup->getReportGroupId()),
				                null,
				                true );
				?>" class="icon <?php echo $action?>"><?php

				echo $this->translate ( 'report_group_button_' . $action );
				?></a>
				   <?php
			endforeach
			;
			?>
			</td>
			</tr>
		<?php endforeach; ?>
	</tbody>
	</table>
</form>
<?php echo $this->paginationControl($this->paginator, 'Sliding', 'partial/pagination.phtml'); ?>
