<a href="<?php echo $this->url(array('module' => 'reports'), null, true); ?>"><?php echo $this->translate('report_index_heading'); ?></a> &raquo;
<a href="<?php echo $this->url(array('module' => 'reports',
                                     'controller' => 'group',
                                     'id' => $this->parent->getCodetemplateId()), null, true);
        ?>">Reports for <?php echo $this->parent->getTitle();?> </a> &raquo;
<a href="<?php echo $this->url(array('module' => 'reports',
                                     'controller' => 'group',
                                     'action' => 'reports',
                                     'id' => $this->parent->getReportGroupId()), null, true);
        ?>"><?php echo $this->parent->getTitle(); ?> Results</a>
<br /><br />
<h1><?php echo $this->translate('report_group_heading'); ?> <?php echo $this->parent->getTitle(); ?></h1>

<table width="100%" class="listing">
<th colspan="4"><?php echo $this->translate('report_result_parameters'); ?></th>
<tr>
	<td><?php echo $this->translate('report_result_parameters_description'); ?></td><td colspan="3"><?php echo $this->parent->getDescription(); ?></td>
</tr>
<tr>
	<td><?php echo $this->translate('report_result_parameters_datefrom'); ?></td><td><?php echo $this->parent->getDateFrom();?></td><td><?php echo $this->translate('report_result_parameters_dateto'); ?></td><td><?php echo $this->parent->getDateFrom();?></td>
</tr>
<tr>
	<td><?php echo $this->translate('report_result_parameters_devicegroups'); ?></td><td colspan="3"><?php echo str_replace("\n", ", ", $this->parent->getGroupsAssignedFormatted());?></td>
</tr>
</table>


<?php
echo $this->paginationControl ( $this->paginator, 'Sliding', 'partial/pagination.phtml' );

$acl = Zend_Registry::get ( 'acl' );

?>
<?php if ($acl->isAllowed($this->currentUser, 'reports_items', 'add')) :?>
<div class="buttons span-18">

	<a id="addlink" class="button small green"
		href="<?php

		echo $this->url(array('action' => 'generate' ), null, false);
		?>"><span><?php echo $this->translate('report_group_button_generate');?></span></a>
</div>
<br />
<?php endif; ?>
<form class="span-19 last" method="get"
	action="<?php

	echo $this->url ( array ('module' => 'reports', 'controller' => 'group', 'action' => 'index', 'id' => $this->parent->getTitle () ), null, true );
	?>">
	<table class="listing">
		<thead>
			<tr>
				<th><?php echo $this->translate('report_index_id');?></th>
				<th><?php echo $this->translate('report_index_date');?></th>
				<th><?php echo $this->translate('report_index_view');?></th>

			</tr>
		</thead>
		<tbody>
		<?php
		foreach ( $this->paginator as $reportItems ) :
			?>
		<tr class="<?php echo $this->cycle(array('odd', 'even'))->next(); ?>">
				<td class="column_id"><?php echo $reportItems->getItemId(); ?></td>
				<td><?php echo $reportItems->getDateAdded(); ?></td>
				<td class="tools">

				  <?php
			// $actions = array ('view', 'deleteresult');


				if ($acl->isAllowed ( $this->currentUser, $reportItems->getResourceId (), 'view' )) :
				?>
					<a
					href="<?php

				echo $this->url ( array ('module' => 'reports', 'controller' => 'group', 'action' => 'view', 'id' => $reportItems->getItemId () ), null, true );
				?>"
					class="icon view"><?php

				echo $this->translate ( 'report_group_button_view' );
				?></a>

				<a
					href="<?php

				    echo $this->url(array('module' => 'reports',
				    					  'controller' => 'group',
				    					  'action' => 'view',
				    					  'id' => $reportItems->getItemId(),
				                          'format' => 'csv' ), null, true );
				?>"
					class="icon csv"><?php

				echo $this->translate ( 'report_group_button_csv' );
				?></a>
				<!--  <a
					href="<?php

				    echo $this->url(array('module' => 'reports',
				    					  'controller' => 'group',
				    					  'action' => 'view',
				    					  'id' => $reportItems->getItemId(),
				                          'format' => 'pdf' ), null, true );
				?>"
					class="icon pdf"><?php

				echo $this->translate ( 'report_group_button_pdf' );
				?></a> -->
				<?php
                    endif; // view allowed
				?>

				<?php
				if (! $acl->isAllowed ( $this->currentUser, $reportItems->getResourceId (), 'delete' )) {
					continue;
				}

				?>
					<a
					href="<?php

				echo $this->url ( array ('module' => 'reports', 'controller' => 'group', 'action' => 'deleteresult', 'id' => $reportItems->getItemId () ), null, true );
				?>"
					class="icon delete"><?php

				echo $this->translate ( 'report_group_button_view' );
				?></a>

				</td>


			</tr>
		<?php endforeach; ?>
	</tbody>
	</table>
</form>

<?php echo $this->paginationControl($this->paginator, 'Sliding', 'partial/pagination.phtml'); ?>

<?php if ($acl->isAllowed($this->currentUser, 'reports_items', 'add')) :?>
<div class="buttons span-18">

	<a id="addlink" class="button small green"
		href="<?php

		echo $this->url(array('action' => 'generate' ), null, false);
		?>"><span><?php echo $this->translate('report_group_button_generate');?></span></a>
</div>
<?php endif; ?>
