<?php echo $this->docType('XHTML1_TRANSITIONAL'); ?>

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <base href="<?php echo $this->baseUrl(); ?>/" />
    <?php echo $this->headTitle('UnwiredAA')?>

	<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js"></script>

	<link rel="stylesheet" media="screen,projection" href="themes/default/styles/blueprint/screen.css" />
	<link rel="stylesheet" media="print" href="themes/default/styles/blueprint/print.css" />

	<link rel="stylesheet" media="all" href="themes/default/styles/style.css" />

    <!--
    	All core meta, link, styles and scripts must be here.
    	Everything else is loaded as needed with the appropriate helpers below.
    -->

	<?php
		echo $this->headLink();
		echo $this->headMeta();
		echo $this->headStyle();
		echo $this->headScript();
	?>
  </head>
  <body>
	<div id="wrapper" class="container">
		<div id="header">
			<div class="userblock">
				<?php echo $this->logInOut(); ?>
			</div>
		</div>

		<?php echo $this->uiMessage(); ?>

		<?php if (Zend_Auth::getInstance()->hasIdentity()) :?>
			<div id="sidenav">
				<?php echo $this->navigation(); ?>
			</div>
		<div id="content" class="ml220">
		<?php else: ?>

		<div id="content">
		<?php endif;?>
			<?php echo $this->layout()->content; ?>
		</div>
	</div>
  </body>
</html>
