<?php echo $this->docType('XHTML1_TRANSITIONAL'); ?>

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <base href="<?php echo $this->baseUrl(); ?>/" />
    <?php echo $this->headTitle('UnwiredAA')?>

	<script type="text/javascript" src="<?php echo $this->httpScheme(); ?>://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js"></script>
	<script type="text/javascript" src="<?php echo $this->httpScheme(); ?>://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/jquery-ui.min.js"></script>

	<link rel="stylesheet" media="screen,projection" href="<?php echo $this->baseUrl("styles/blueprint/screen.css"); ?>" />
	<link rel="stylesheet" media="print" href="<?php echo $this->baseUrl("styles/blueprint/print.css"); ?>" />
	<!--[if lt IE 8]>
    	<link rel="stylesheet" href="<?php echo $this->baseUrl("styles/blueprint/ie.css"); ?>" type="text/css" media="screen, projection" />
  	<![endif]-->
	<link rel="stylesheet" media="all" href="<?php echo $this->baseUrl("themes/{$this->theme}/styles/style.css"); ?>" />

    <!--
    	All core meta, link, styles and scripts must be here.
    	Everything else is loaded as needed with the appropriate helpers below.
    -->
    <script type="text/javascript" src="<?php echo $this->baseUrl("scripts/unwired.js"); ?>"></script>

	<?php
		echo $this->headLink();
		echo $this->headMeta();
		echo $this->headStyle();
		echo $this->headScript();
	?>
  </head>
  <body>
	<div id="wrapper" class="container">
		<div id="header">
			<div class="userblock">
				<?php echo $this->logInOut(); ?>
			</div>
		</div>

		<?php echo $this->uiMessage(); ?>

		<?php if (Zend_Auth::getInstance()->hasIdentity()) :?>
			<div id="sidenav" class="span-5">
				<?php echo $this->navigation(); ?>
			</div>
		<div id="content" class="span-19 last">
		<?php else: ?>

		<div id="content" class="span-24 last">
		<?php endif;?>
			<?php echo $this->layout()->content; ?>
		</div>
	</div>
  </body>
</html>
