<div class="widget links-widget">
        	<?php
        	    foreach ($this->deviceLinks as $link) {
        	        $escape = true;
        	        if (preg_match('/\<.*\>/i', $link['content'])) {
        	            $escape = false;
        	        }
                    echo $this->formHref(array('name' => 'link' . rand(),
                                               'escape' => $escape,
                                               'attribs' => $link));
        	    }
        	?>
</div>