<?php
/**
* Unwired AA GUI
*
* Author & Copyright (c) 2011 Unwired Networks GmbH
* alexander.szlezak@unwired.at
*
* Licensed under the terms of the Affero Gnu Public License version 3
* (AGPLv3 - http://www.gnu.org/licenses/agpl.html) or our proprietory
* license available at http://www.unwired.at/license.html
*/
?>
<h1><?php
	echo sprintf($this->translate('captive_index_edit_heading_edit'), $this->splashPage->getTitle());
	$settings = $this->splashPage->getTemplate()->getSettings();
?></h1>
<?php
    $this->headScript()->appendFile($this->baseUrl('scripts/nicedit/nicEdit.js'));
    $this->headScript()->captureStart();
?>
	$(document).ready(function(){
		$('div.tabs').tabs();
		$('div.tabs').removeClass('ui-corner-all');
		$('.accordion').accordion({
			autoHeight: false,
			collapsible: true
		});

		nicEditors.allTextAreas({iconsPath : '<?php echo $this->baseUrl('scripts/nicedit/nicEditorIcons.gif'); ?>'});
	});
<?php
    $this->headScript()->captureEnd();
?>
<form method="post" action="<?php echo $_SERVER['REQUEST_URI']; ?>">
    <div class="accordion span-19 last">
    	<?php
    	    $contentCounter = 0;
    	    foreach ($this->contents as $column => $languageContents) :
    	?>
    	<h3 class="span-19 last"><a href="#"><?php echo $this->translate('captive_content_splashpage_column_' .strtolower($column));?></a></h3>
		<div class="span-19 tabs formelement">
			<ul>
    		<?php foreach ($settings['language_ids'] as $languageId) :?>
    			<li><a href="<?php echo "#{$column}-{$languageId}"; ?>"><?php echo $this->languages[$languageId]->getName(); ?></a></li>
    		<?php endforeach; ?>
    		</ul>
    		<?php foreach ($languageContents as $languageId => $columnContents) :?>
			<div id="<?php echo "{$column}-{$languageId}"; ?>">
				<?php
				    $columnStartCounter = $contentCounter;
				    foreach ($columnContents as $content) :
					    if (!$content->isEditable()) {
                            continue;
					    }

				        $contentCounter++;
				?>
					<div class="span-18 last">
						<!-- start content edit -->

						<?php
						    echo $this->widgetAdmin($content, array('prefix' => "content[{$contentCounter}]", 'languageId' => $languageId));
						?>

						<!-- end content edit -->
					</div>
			    <?php
				    endforeach; // $columnContents
            	    if ($columnStartCounter == $contentCounter) :
            	?>
            		<div class="formelement span-17 nocontent">
            			<h3><?php echo $this->translate('captive_content_splashpage_column_nocontent'); ?></h3>
            		</div>
            	<?php
            	    endif;
            	?>
			</div>
    		<?php endforeach; // $languageContents ?>
		</div>
    	<?php
    	    endforeach; // $this->contents
    	?>
    </div>
    <div class="buttons">
    	<span class="button green">
    		<input type="submit" value="<?php echo $this->translate('captive_content_splashpage_save'); ?>"/>
    	</span>

    	<a href="<?php echo $this->refererUrl; ?>" class="button blue"><span><?php echo $this->translate('captive_content_template_cancel'); ?></span></a>
    </div>
</form>