<h1><?php
	if ($this->entity->getSplashId()) {
		echo sprintf($this->translate('captive_index_edit_heading_edit'), $this->entity->getTitle());
	} else {
		echo $this->translate('captive_index_edit_heading_add');
	}
?></h1>
<?php
	$this->headScript()->appendFile($this->baseUrl('scripts/jstree/jquery.jstree.js'));
	$this->headLink()->appendStylesheet($this->baseUrl('scripts/jstree/themes/default/style.css'));

	$this->headScript()->captureStart();

?>
var adminGroups = <?php echo Zend_Json::encode($this->currentUser->getGroupsAssigned());?>;

$(function () {
	$("label[for=group_id]").siblings('label').remove();
	$("label[for=group_id]").after($('.grouptree'));

	var init_select = new Array();

<?php
    if ($this->entity->getGroupId()):
?>
	init_select.push('group_<?php echo $this->entity->getGroupId(); ?>');
<?php
    endif;
?>

	function showTemplateSelectGroup()
	{
		if ($('#template_id option').length > 0) {
			if (!$('#template_id').parent().find('ul.errors').length) {
				return;
			}

			var ulErrors = !$('#template_id').parent().find('ul.errors');
			if ($(ulErrors).children().length == 1) {
				$(ulErrors).remove();
			} else {
				$(ulErrors).find('li.nogroup').remove();
			}
		} else {
			if (!$('#template_id').parent().find('ul.errors').length) {
				$('#template_id').parent().append('<ul class="errors" />');
			}

			$('#template_id').parent()
							  .find('ul.errors')
							    .prepend('<li class="nogroup"><?php echo $this->translate('captive_index_edit_form_template_select_group');?></li>');
		}
	}

    $(".grouptree")
        .jstree({
            "plugins" : ["themes","html_data","ui"],
            "core" : { "initially_open" : init_select.length ? init_select : 'group_1' },
            "ui" : { select_multiple_modifier: 'off',
            		 disable_selecting_children: false,
					 select_limit : 1,
					 "initially_select" : init_select
					}
        })
        .bind("select_node.jstree", function (event, data) {
			var groupId = data.rslt.obj.attr("id").replace(/[^\d]+/gi,'');

			$('input[name=group_id]').val(groupId);

			var oldTemplate = $('#template_id').val() ? $('#template_id').val() : '<?php echo $this->entity->getTemplateId(); ?>';

			$('#template_id').children().remove();
			$.ajax({
				'url': '<?php echo $this->url(array('module' => 'captive',
				                                    'controller' => 'index',
				                                    'action' => 'group-templates'),
				                             'default',
				                             true); ?>/id/' + groupId,
				'success': function(data) {
					$.each(data, function(idx, elem) {
						$('#template_id').append('<option value="' + elem.id + '">'+elem.name+'</option>');
					});

					var optionSelected = $('select#template_id option[value=<?php echo $this->entity->getTemplateId(); ?>]');
					if (!optionSelected.length) {
						var optionSelected = $('select#template_id option[value='+oldTemplate+']');
					}

					$(optionSelected).attr('selected','selected');
					showTemplateSelectGroup();
				}
			});
	     });

	     showTemplateSelectGroup();

});
<?php
	$this->headScript()->captureEnd();

	echo $this->form;
?>
<div class="grouptree span-8">
	<?php echo $this->tree($this->rootGroup, null, array('prefix' => 'group_')); ?>
</div>